spring:
  application:
    name: trianel

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    baseline-on-migrate: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus,configprops,env,threaddump,loggers,conditions,mappings,shutdown
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
        add-additional-paths: true
debug: true
