name: integration

on:
  pull_request:

  push:
    branches:
      - main

jobs:
  sonarlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "liberica"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew sonarlintMain sonarlintTest

  test:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "liberica"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test

  bootBuildImage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "liberica"
          java-version: "21"
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew bootBuildImage
